  name: IOS CI

  on: push
  #     branches: [ "master" ]
  #   pull_request:
  #     branches: [ "master" ]

  jobs:
    build:
      permissions: write-all
      name: Build IPA
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build ios --release --no-codesign
      - name: Push IPA to Releases
        uses: actions/upload-artifact@v3
        with:
          path: "build/ios/iphoneos/Runner.app"
          name: v1.0.${{ github.run_number }}
    
